#Step 5 - Image Conversion
Convert windows to images, with labels for CNN Classification Model

Data Cleaning

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load data
markov_path = '/content/qci_nist_results_nonrandom_part1 (0-149).csv'
qrng_path = '/content/qci_random_nist_window_results.csv'

qrng_df = pd.read_csv(qrng_path)
print(f"QRNG windows loaded: {len(qrng_df)}")

markov_df = pd.read_csv(markov_path)
print(f"Markov windows loaded: {len(markov_df)}")

QRNG windows loaded: 1606
Markov windows loaded: 1606

In [ ]:
qrng_df['FrequencyTest'].value_counts()
markov_df['FrequencyTest'].value_counts()

FrequencyTest
(np.float64(0.0), np.False_)                        734
(np.float64(7.642907724239892e-132), np.False_)       2
(np.float64(0.142337350916465), np.True_)             2
(np.float64(8.328891070019154e-45), np.False_)        2
(np.float64(2.6223207525579242e-278), np.False_)      2
                                                   ...
(np.float64(2.628493491909349e-42), np.False_)        1
(np.float64(2.0879423728579815e-71), np.False_)       1
(np.float64(1.3778424835091851e-18), np.False_)       1
(np.float64(6.058539660047944e-29), np.False_)        1
(np.float64(1.7686124267515346e-303), np.False_)      1
Name: count, Length: 855, dtype: int64

In [ ]:
qrng_df.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,ApproxEntropy,LinearComplexity,Non-overlapping Template Matching Test,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test
0,0,0,1204224,"(np.float64(0.359280935625237), np.True_)","(np.float64(0.7357176414832521), np.True_)","(np.float64(0.5444221810095644), np.True_)","(np.float64(0.8117233659333889), np.True_)","(0.294971693468063, True)","(np.float64(0.7915865173456221), np.True_)","(np.float64(0.6074460193503417), np.True_)","(np.float64(0.9050105055464273), np.True_)","(np.float64(0.9224211512043566), np.True_)","(np.float64(0.08669549416265646), np.True_)","(np.float64(0.5435484256246601), np.True_)","((np.float64(0.42398414203107543), np.True_), ...","(np.float64(0.3044800742020973), np.True_)","(np.float64(0.6220455262622973), np.True_)",True,True
1,1,602112,1806336,"(np.float64(0.8496665912664424), np.True_)","(np.float64(0.12454467639141996), np.True_)","(np.float64(0.4582052940192318), np.True_)","(np.float64(0.7089447567580025), np.True_)","(0.3594425151007414, True)","(np.float64(0.5718721522592609), np.True_)","(np.float64(0.5592809343634678), np.True_)","(np.float64(0.35547630267536356), np.True_)","(np.float64(0.5604825472252033), np.True_)","(np.float64(0.18355063580534015), np.True_)","(np.float64(0.8604676028183248), np.True_)","((np.float64(0.22954593040149146), np.True_), ...","(np.float64(0.9934443830698378), np.True_)","(np.float64(0.9391327056958756), np.True_)",True,True
2,2,1204224,2408448,"(np.float64(0.13221726828141034), np.True_)","(np.float64(0.02427334592954829), np.True_)","(np.float64(0.4384446484765915), np.True_)","(np.float64(0.27695250826820433), np.True_)","(0.38644815561397244, True)","(np.float64(0.32212279931705523), np.True_)","(np.float64(0.05228890897646408), np.True_)","(np.float64(0.1690566973509191), np.True_)","(np.float64(0.4123379573173525), np.True_)","(np.float64(0.7007474272671587), np.True_)","(np.float64(0.007499960749685348), np.False_)","((np.float64(0.3234554110086947), np.True_), (...","(np.float64(0.2091897303966805), np.True_)","(np.float64(0.11486757120089133), np.True_)",True,True
3,3,1806336,3010560,"(np.float64(0.11159274062998492), np.True_)","(np.float64(0.012979115281611565), np.True_)","(np.float64(0.985072637466174), np.True_)","(np.float64(0.008641446278167784), np.False_)","(0.7848235618452885, True)","(np.float64(0.5493423240533905), np.True_)","(np.float64(0.009779660100177256), np.False_)","(np.float64(0.23075156506030495), np.True_)","(np.float64(0.29497939354961206), np.True_)","(np.float64(0.9707833895164584), np.True_)","(np.float64(0.10393076332363901), np.True_)","((np.float64(0.7828772228362966), np.True_), (...","(np.float64(0.05551263330350456), np.True_)","(np.float64(0.17302162819562167), np.True_)",True,True
4,4,2408448,3612672,"(np.float64(0.894157632364297), np.True_)","(np.float64(0.17213544190034755), np.True_)","(np.float64(0.32414469043177396), np.True_)","(np.float64(0.47555502130448446), np.True_)","(0.8258256241752079, True)","(np.float64(0.8057954274416456), np.True_)","(np.float64(0.018078155002407288), np.True_)","(np.float64(0.7599547805838457), np.True_)","(np.float64(0.10550839348375132), np.True_)","(np.float64(0.9900176291166901), np.True_)","(np.float64(0.2770272644991627), np.True_)","((np.float64(0.7157681868796218), np.True_), (...","(np.float64(0.7990828588963874), np.True_)","(np.float64(0.9086050699248187), np.True_)",True,True

In [ ]:
qrng_df['sourceLabel'] = 'Random'

In [ ]:
markov_df['sourceLabel'] = 'Non-Random'

In [ ]:
mapping = {' np.True_)': True, ' np.False_)': False, ' True)': True, ' False)': False}

In [ ]:
mapping[qrng_df['FrequencyTest'][0].split(',')[1]]
mapping[markov_df['FrequencyTest'][0].split(',')[1]]

False

In [ ]:
for col in qrng_df.columns:
  if qrng_df[col].dtype == 'object' and qrng_df[col].str.contains('np.True_\)|np.False_\)').any():
    qrng_df[col] = qrng_df[col].apply(lambda x: mapping[x.split(',')[1]])

<>:2: SyntaxWarning: invalid escape sequence '\)'
<>:2: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipython-input-2935612942.py:2: SyntaxWarning: invalid escape sequence '\)'
  if qrng_df[col].dtype == 'object' and qrng_df[col].str.contains('np.True_\)|np.False_\)').any():

In [ ]:
for col in markov_df.columns:
  if markov_df[col].dtype == 'object' and markov_df[col].str.contains('np.True_\)|np.False_\)').any():
    markov_df[col] = markov_df[col].apply(lambda x: mapping[x.split(',')[1]])

<>:2: SyntaxWarning: invalid escape sequence '\)'
<>:2: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipython-input-1462691370.py:2: SyntaxWarning: invalid escape sequence '\)'
  if markov_df[col].dtype == 'object' and markov_df[col].str.contains('np.True_\)|np.False_\)').any():

In [ ]:
mapping[qrng_df['MatrixRank'][0].split(',')[1]]

True

In [ ]:
mapping[markov_df['MatrixRank'][0].split(',')[1]]

False

In [ ]:
qrng_df['MatrixRank'] = qrng_df['MatrixRank'].apply(lambda x: mapping[x.split(',')[1]])

In [ ]:
markov_df['MatrixRank'] = markov_df['MatrixRank'].apply(lambda x: mapping[x.split(',')[1]])

In [ ]:
qrng_df.to_csv("final_random_cleaned.csv", index=False)

In [ ]:
markov_df.to_csv("final_nonrandom_cleaned.csv", index=False)

In [ ]:
qrng_df.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,ApproxEntropy,LinearComplexity,Non-overlapping Template Matching Test,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel
0,0,0,1204224,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,Random
1,1,602112,1806336,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,Random
2,2,1204224,2408448,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,Random
3,3,1806336,3010560,True,True,True,False,True,True,False,True,True,True,True,True,True,True,True,True,Random
4,4,2408448,3612672,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,Random

In [ ]:
markov_df.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,ApproxEntropy,LinearComplexity,Non-overlapping Template Matching Test,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel
0,0,0,1204224,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random
1,1,602112,1806336,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,Non-Random
2,2,1204224,2408448,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,Non-Random
3,3,1806336,3010560,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random
4,4,2408448,3612672,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random

# Labelling

In [ ]:
cleaned_qrng = pd.read_csv("/content/final_random_cleaned.csv")
cleaned_markov = pd.read_csv("/content/final_nonrandom_cleaned.csv")

In [ ]:
cleaned_qrng.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,ApproxEntropy,LinearComplexity,Non-overlapping Template Matching Test,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel
0,0,0,1204224,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,Random
1,1,602112,1806336,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,Random
2,2,1204224,2408448,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,Random
3,3,1806336,3010560,True,True,True,False,True,True,False,True,True,True,True,True,True,True,True,True,Random
4,4,2408448,3612672,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,Random

In [ ]:
cleaned_qrng.columns

Index(['window_index', 'start_bit', 'end_bit', 'FrequencyTest',
       'BlockFrequency', 'RunTest', 'LongestRun', 'MatrixRank', 'Spectral',
       'Universal', 'ApproxEntropy', 'LinearComplexity',
       'Non-overlapping Template Matching Test',
       'Overlappong Template Matching Test', 'Serial Test',
       'Cumulative Sums (Forward)', 'Cumulative Sums (Backward)',
       'Random Excursion Test', 'Random Excursion Variant Test',
       'sourceLabel'],
      dtype='object')

In [ ]:
cleaned_qrng['Cumulative Sums'] = cleaned_qrng['Cumulative Sums (Forward)'] & cleaned_qrng['Cumulative Sums (Backward)']

In [ ]:
cleaned_markov.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,ApproxEntropy,LinearComplexity,Non-overlapping Template Matching Test,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel
0,0,0,1204224,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random
1,1,602112,1806336,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,Non-Random
2,2,1204224,2408448,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,Non-Random
3,3,1806336,3010560,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random
4,4,2408448,3612672,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random

In [ ]:
# List of NIST test columns
nist_tests = [
    'FrequencyTest',
    'BlockFrequency',
    'RunTest',
    'LongestRun',
    'MatrixRank',
    'Spectral',
    'Universal',
    'ApproxEntropy',
    'LinearComplexity',
    'Non-overlapping Template Matching Test',
    'Overlappong Template Matching Test',
    'Serial Test',
    'Cumulative Sums',
    'Random Excursion Test',
    'Random Excursion Variant Test'
]

# Count how many of these tests are True for each row
cleaned_qrng['nist_passing'] = cleaned_qrng[nist_tests].sum(axis=1)

# Create a "Critical tests" column — True if all 3 pass (FrequencyTest, RunTest, Spectral)
cleaned_qrng['Critical tests'] = (
    cleaned_qrng['FrequencyTest'] &
    cleaned_qrng['RunTest'] &
    cleaned_qrng['Spectral']
)

In [ ]:
cleaned_qrng.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,...,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel,Cumulative Sums,nist_passing,Critical tests
0,0,0,1204224,True,True,True,True,True,True,True,...,True,True,True,True,True,True,Random,True,15,True
1,1,602112,1806336,True,True,True,True,True,True,True,...,True,True,True,True,True,True,Random,True,15,True
2,2,1204224,2408448,True,True,True,True,True,True,True,...,False,True,True,True,True,True,Random,True,14,True
3,3,1806336,3010560,True,True,True,False,True,True,False,...,True,True,True,True,True,True,Random,True,13,True
4,4,2408448,3612672,True,True,True,True,True,True,True,...,True,True,True,True,True,True,Random,True,15,True

In [ ]:
cleaned_qrng['nist_passing'].value_counts()

nist_passing
15    1180
14     345
13      67
12      13
11       1
Name: count, dtype: int64

In [ ]:
cleaned_qrng['Critical tests'].value_counts()

Critical tests
True     1555
False      51
Name: count, dtype: int64

In [ ]:
cleaned_qrng[cleaned_qrng['nist_passing'] <= 12]

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,...,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel,Cumulative Sums,nist_passing,Critical tests
444,444,267337728,268541952,True,True,True,True,False,True,True,...,True,True,True,True,False,False,Random,True,12,True
445,445,267939840,269144064,True,True,True,True,False,True,True,...,True,True,True,True,False,False,Random,True,12,True
461,461,277573632,278777856,False,True,True,True,True,True,True,...,True,True,False,False,True,False,Random,False,12,False
734,734,441950208,443154432,False,True,True,True,True,True,True,...,True,True,False,True,False,False,Random,False,11,False
886,886,533471232,534675456,False,True,True,True,True,True,False,...,True,True,False,False,True,True,Random,False,12,False
931,931,560566272,561770496,True,True,True,True,True,False,True,...,True,True,True,True,False,False,Random,True,12,False
979,979,589467648,590671872,True,True,False,True,True,True,True,...,True,True,True,True,False,False,Random,True,12,False
1004,1004,604520448,605724672,True,True,True,True,True,True,True,...,False,True,True,True,False,False,Random,True,12,True
1021,1021,614756352,615960576,True,True,True,True,True,True,True,...,False,False,True,True,True,True,Random,True,12,True
1056,1056,635830272,637034496,False,True,True,True,True,True,True,...,True,True,False,True,True,True,Random,False,12,False
1081,1081,650883072,652087296,False,True,True,True,True,True,True,...,True,True,False,False,False,True,Random,False,12,False
1360,1360,818872320,820076544,False,True,True,True,True,True,True,...,True,True,True,False,False,True,Random,False,12,False
1433,1433,862826496,864030720,False,True,True,True,True,True,True,...,True,True,False,False,False,True,Random,False,12,False
1582,1582,952541184,953745408,True,True,True,True,False,True,True,...,True,True,True,True,False,False,Random,True,12,True

In [ ]:
cleaned_markov.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,ApproxEntropy,LinearComplexity,Non-overlapping Template Matching Test,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel
0,0,0,1204224,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random
1,1,602112,1806336,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,Non-Random
2,2,1204224,2408448,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,Non-Random
3,3,1806336,3010560,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random
4,4,2408448,3612672,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,Non-Random

In [ ]:
cleaned_markov['Cumulative Sums'] = cleaned_markov['Cumulative Sums (Forward)'] & cleaned_markov['Cumulative Sums (Backward)']

In [ ]:
cleaned_markov.columns

Index(['window_index', 'start_bit', 'end_bit', 'FrequencyTest',
       'BlockFrequency', 'RunTest', 'LongestRun', 'MatrixRank', 'Spectral',
       'Universal', 'ApproxEntropy', 'LinearComplexity',
       'Non-overlapping Template Matching Test',
       'Overlappong Template Matching Test', 'Serial Test',
       'Cumulative Sums (Forward)', 'Cumulative Sums (Backward)',
       'Random Excursion Test', 'Random Excursion Variant Test', 'sourceLabel',
       'Cumulative Sums'],
      dtype='object')

In [ ]:
# List of NIST test columns
nist_tests = [
    'FrequencyTest',
    'BlockFrequency',
    'RunTest',
    'LongestRun',
    'MatrixRank',
    'Spectral',
    'Universal',
    'ApproxEntropy',
    'LinearComplexity',
    'Non-overlapping Template Matching Test',
    'Overlappong Template Matching Test',
    'Serial Test',
    'Cumulative Sums',
    'Random Excursion Test',
    'Random Excursion Variant Test'
]

# Count how many of these tests are True for each row
cleaned_markov['nist_passing'] = cleaned_markov[nist_tests].sum(axis=1)

# Create a "Critical tests" column — True if all 3 pass (FrequencyTest, RunTest, Spectral)
cleaned_markov['Critical tests'] = (
    cleaned_markov['FrequencyTest'] &
    cleaned_markov['RunTest'] &
    cleaned_markov['Spectral']
)

In [ ]:
cleaned_markov.head()

,window_index,start_bit,end_bit,FrequencyTest,BlockFrequency,RunTest,LongestRun,MatrixRank,Spectral,Universal,...,Overlappong Template Matching Test,Serial Test,Cumulative Sums (Forward),Cumulative Sums (Backward),Random Excursion Test,Random Excursion Variant Test,sourceLabel,Cumulative Sums,nist_passing,Critical tests
0,0,0,1204224,False,False,False,False,False,False,False,...,False,False,False,False,False,True,Non-Random,False,2,False
1,1,602112,1806336,False,False,False,False,False,False,False,...,False,False,False,False,True,True,Non-Random,False,3,False
2,2,1204224,2408448,False,False,False,False,False,False,False,...,False,False,False,False,True,True,Non-Random,False,3,False
3,3,1806336,3010560,False,False,False,False,False,False,False,...,False,False,False,False,False,True,Non-Random,False,2,False
4,4,2408448,3612672,False,False,False,False,False,False,False,...,False,False,False,False,False,True,Non-Random,False,2,False

In [ ]:
cleaned_markov['nist_passing'].value_counts()

nist_passing
2    819
3    688
1     70
4     24
5      3
0      2
Name: count, dtype: int64

In [ ]:
cleaned_markov['Critical tests'].value_counts()

Critical tests
False    1606
Name: count, dtype: int64

In [ ]:
cleaned_qrng['Nist_label'] = cleaned_qrng['nist_passing'].apply(lambda x: 'Non-Random' if x <= 13 else 'Random')

In [ ]:
cleaned_markov['Nist_label'] = 'Non-Random'

In [ ]:
cleaned_markov['final_label'] = 'Non-Random'

In [ ]:
cleaned_qrng['final_label'] = cleaned_qrng['Nist_label']

In [ ]:
cleaned_qrng['final_label'].value_counts()

final_label
Random        1525
Non-Random      81
Name: count, dtype: int64

In [ ]:
cleaned_markov['final_label'].value_counts()

final_label
Non-Random    1606
Name: count, dtype: int64

In [ ]:
final_df = pd.concat([cleaned_qrng, cleaned_markov], ignore_index=True)
len(final_df)

3212

In [ ]:
final_df.to_csv("final_combined_labelled.csv", index=False)